on:
  push:
    branches:
      - main

jobs:
  open_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código
      uses: actions/checkout@v3

    - name: Criar e abrir PRs
      run: |
        git checkout main
        git pull origin main

        branches=$(git branch -r --list "origin/rc-*" | sed 's/origin\///')
        for branch in $branches
        do
          merge_branch = merge-$branch
          git checkout -b $merge_branch
          git push -u origin $merge_branch
          hub pull-request -b merge_branch -h $branch -m "Atualização de $branch"
          git checkout main
        done
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
