name: Abrir PRs para branches rc-*

on:
  push:
    branches:
      - main

jobs:
  open_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código
      uses: actions/checkout@v2

    - name: Criar e abrir PRs
      run: |
        git checkout main
        git pull origin main

        branches=$(git branch -r --list "origin/rc-*" | sed 's/origin\///')
        for branch in $branches
        do
          git checkout -b $branch
          git push -u origin $branch

          title="Atualização de $branch"
          body="Atualização de $branch"

          response=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "title": "'"${title}"'",
              "body": "'"${body}"'",
              "head": "'"${branch}"'",
              "base": "main"
            }' \
            "https://api.github.com/repos/${{ github.repository }}/pulls")

          echo "PR criado: $response"

          git checkout main
        done
